name: "Run tests"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run_all_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install dependencies"
        timeout-minutes: 4
        run: |
          sudo apt-get install -y \
            git make gcc rsync bison flex cpio bc libelf-dev gawk fdisk wget lbzip2 \
            xz-utils dosfstools libssl-dev libncurses-dev qemu-system-x86

      - name: "Run test script"
        timeout-minutes: 12
        run: |
          echo 'export MAKE_NUM_OF_THREADS=$(($(nproc) + 1))' > config.sh
          make test
